### ISSUE TITLE
The loss plateaus after 100 Epoch

### ISSUE THREAD

**Issue by ROZBEH** [supernlogn/squeezeDetTL#3]
Hi there,

Using the original setting the loss starts at about 33 but plateaus at about 3.0.
Any recommendations?
I'm curious what's the ultimate loss that you get after 100 epochs.

Thank you.

**Comment by supernlogn** [comment]
In which dataset?
If you are using Pascal VOC the problem is that training and testing data are 50-50. So to achieve better results (and also meaningful) you can try changing it to something like 80-20 or 90-10.
For losses after many steps, you can see the paper in ArXiv: https://arxiv.org/abs/1811.04863
table 2 and figures 6 - 10.
This work was not focused on training for many epochs, but rather on how to reuse networks capable of running in embedded devices and retrain them as fast as possible.

Thank you for asking.

**Comment by ROZBEH** [comment]
Thanks for the link to the paper. Even with the KITTI dataset and coco dataset, I cannot bring the loss lower than 2.5. Any idea what might be happening? I used different batch sizes and changed the anchors as well but no avail. Also I am initializing the weights with imagenet weights.

**Comment by supernlogn** [comment]
I had the same issue when I normalized with the wrong constants for the mean and standard deviation. The authors of squeezeDet, use squeezeNet which is first trained in ImageNet, so they use the normalization constants from the training of squeezeNet in ImageNet to achieve the results that are presented for squeezeDet in KITTI.

**Comment by ROZBEH** [comment]
Can you please point me to where the normalization happens?
I didn't notice such a normalization in the code base

**Comment by supernlogn** [comment]
Here is the line:
[https://github.com/supernlogn/squeezeDetTL/blob/master/src/datasets/imdb.py#L59](https://github.com/supernlogn/squeezeDetTL/blob/master/src/datasets/imdb.py#L59)

It is done automatically when loading the dataset of your choice KITTI/MS COCO/PASCAL VOC

**Comment by ROZBEH** [comment]
Got it, thanks for the pointer.
